version: '3.7'
services:
  jenkins:
    restart: 'unless-stopped'
    build: .
    ports:
        - '8080:8080'
    volumes:
      - ./data:/bitnami/jenkins
        - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      resources:
        limits:
          memory: 1024M
