services:
        cicd_postgres:
                container_name: cicd_postgres
                image: postgres:12
                restart: 'unless-stopped'
                command: postgres -c 'max_connections=1000'
                environment:
                        POSTGRES_PASSWORD: cicd_is_cool
                        POSTGRES_USER: cicd
                volumes:
                        - ./data:/var/lib/postgresql/data
                ports:
                        - "0.0.0.0:5432:5432"
