services:
  proxy:
    networks:
      - internal
  odoo_base:
    privileged: True
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal

networks:
    internal:
        name: "${CICD_NETWORK_NAME}_internal"
